name: kellnr-ci
on:
  release:
    types:
      - published


jobs:
  build-and-push-image:
    name: Build and Push Image
    if: github.event_name == 'release'
    runs-on: ubuntu-24.04
    permissions:
      packages: write
      contents: read
    env:
      IMAGE: ghcr.io/matt-mai/kellnr

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Extract Version
        run: |
          echo "RELEASE_VERSION=${GITHUB_REF#refs/*/v}" >> $GITHUB_ENV
          echo $RELEASE_VERSION

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v3
      
      - name: Log in to registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u $ --password-stdin

      - name: Docker Build & Push
        run: chmod u+x build_and_push.sh && ./build_and_push.sh $IMAGE $RELEASE_VERSION
        working-directory: docker
